apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "biblioteca.fullname" . }}
  labels:
    {{- include "biblioteca.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "biblioteca.selectorLabels" . | nindent 6 }}
